---
# tasks file for sudoers
- name: Add user to sudoers
  lineinfile:
    dest: /etc/sudoers.d/10_access
    line: '"{{ user_name }}" ALL=(ALL) ALL'
    create: yes
    owner: root
    group: root
    mode: '0440'
    validate: /usr/sbin/visudo -cf %s