---
# tasks file for website
- name: install httpd
  package:
    name: httpd
    state: latest

- name: start httpd
  service:
    enable: yes
    state: started

- name: update index
  template:
    src: templates/index.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0664
  